name: Deploy with Approval

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build
        run: echo "Building the application..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: DEV   
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production..."
