name: my first workflow
on: 
  push:
   branches:
         - '*'

jobs:
  show-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo "Environment is ${{ vars.APP_ENV }}"

